# Validação

In [1]:
from pathlib import Path

from reporting.cross_validation import (
    load_and_display_cross_validation_statistics,
)

In [2]:
artifact_directory = Path("_artifacts") / "rosids"

## Decision Tree

In [3]:
load_and_display_cross_validation_statistics(
    artifact_directory / "decision_tree",
)

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,34fdea955c76,passthrough,entropy,20.0,10,1,0.941256,0.943354,0.941438,0.97135 ± 0.00058,0.94431 ± 0.00155,0.93997 ± 0.00120,0.94202 ± 0.00116,0.98059 ± 0.00049,0.93427 ± 0.00178,0.95823 ± 0.00084,0.93997 ± 0.00120
1,1cbc00d06004,passthrough,gini,20.0,2,1,0.942521,0.941641,0.941581,0.97122 ± 0.00012,0.94617 ± 0.00110,0.93798 ± 0.00106,0.94191 ± 0.00053,0.97449 ± 0.00040,0.91705 ± 0.00087,0.95801 ± 0.00018,0.93798 ± 0.00106
2,30aa88389da9,passthrough,entropy,20.0,5,5,0.941364,0.942433,0.940863,0.97135 ± 0.00038,0.94461 ± 0.00190,0.93873 ± 0.00104,0.94155 ± 0.00080,0.98442 ± 0.00029,0.94591 ± 0.00162,0.95820 ± 0.00054,0.93873 ± 0.00104
3,344b1a951d1f,passthrough,entropy,20.0,2,5,0.941364,0.942433,0.940863,0.97135 ± 0.00038,0.94461 ± 0.00190,0.93873 ± 0.00104,0.94155 ± 0.00080,0.98442 ± 0.00029,0.94591 ± 0.00162,0.95820 ± 0.00054,0.93873 ± 0.00104
4,d2d0367e6a3c,passthrough,entropy,20.0,10,5,0.941364,0.942433,0.940863,0.97135 ± 0.00038,0.94461 ± 0.00190,0.93873 ± 0.00104,0.94155 ± 0.00080,0.98442 ± 0.00029,0.94591 ± 0.00162,0.95820 ± 0.00054,0.93873 ± 0.00104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,4dc396c7cda5,random_over_sampler,entropy,10.0,2,1,0.917735,0.913140,0.912286,0.95512 ± 0.00155,0.89181 ± 0.00419,0.94742 ± 0.00085,0.91439 ± 0.00293,0.98962 ± 0.00034,0.94236 ± 0.00032,0.93593 ± 0.00210,0.94742 ± 0.00085
68,cb8e526a270c,random_over_sampler,entropy,10.0,10,1,0.917574,0.913109,0.912350,0.95512 ± 0.00154,0.89171 ± 0.00404,0.94743 ± 0.00082,0.91434 ± 0.00282,0.98967 ± 0.00037,0.94247 ± 0.00044,0.93592 ± 0.00209,0.94743 ± 0.00082
69,8c9903eea9c6,random_over_sampler,entropy,10.0,2,5,0.917309,0.913251,0.911887,0.95500 ± 0.00159,0.89123 ± 0.00404,0.94766 ± 0.00070,0.91415 ± 0.00282,0.99008 ± 0.00023,0.94360 ± 0.00046,0.93578 ± 0.00215,0.94766 ± 0.00070
70,b3ec13d325c9,random_over_sampler,entropy,10.0,10,5,0.917309,0.913251,0.911887,0.95500 ± 0.00159,0.89123 ± 0.00404,0.94766 ± 0.00070,0.91415 ± 0.00282,0.99008 ± 0.00023,0.94360 ± 0.00046,0.93578 ± 0.00215,0.94766 ± 0.00070
71,d4570f105ea1,random_over_sampler,entropy,10.0,5,5,0.917309,0.913251,0.911887,0.95500 ± 0.00159,0.89123 ± 0.00404,0.94766 ± 0.00070,0.91415 ± 0.00282,0.99008 ± 0.00023,0.94360 ± 0.00046,0.93578 ± 0.00215,0.94766 ± 0.00070

,configuration_id,seed,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,passthrough,gini,10.0,2,1,0.967113,0.938699,0.923437,0.930696,0.988323,0.932683,0.951987,0.923437
1,f555fc62ae6a,32,passthrough,gini,10.0,2,1,0.967076,0.938240,0.923722,0.930679,0.987889,0.930775,0.951933,0.923722
2,f555fc62ae6a,59,passthrough,gini,10.0,2,1,0.965714,0.938645,0.916663,0.926751,0.987226,0.927420,0.949949,0.916663
3,c55590c695f3,27,passthrough,gini,10.0,2,5,0.966848,0.938318,0.922481,0.930033,0.989025,0.936013,0.951595,0.922481
4,c55590c695f3,32,passthrough,gini,10.0,2,5,0.967031,0.938408,0.923228,0.930467,0.988397,0.932936,0.951866,0.923228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,d5925f8116be,32,random_over_sampler,entropy,NaN,10,1,0.965403,0.923907,0.939737,0.931335,0.968358,0.902927,0.949751,0.939737
212,d5925f8116be,59,random_over_sampler,entropy,NaN,10,1,0.965494,0.923284,0.940150,0.931164,0.968438,0.902953,0.949905,0.940150
213,5a7ac466ea55,27,random_over_sampler,entropy,NaN,10,5,0.965823,0.914836,0.954685,0.932976,0.978856,0.922386,0.950778,0.954685
214,5a7ac466ea55,32,random_over_sampler,entropy,NaN,10,5,0.966317,0.915966,0.953870,0.933323,0.978620,0.923350,0.951451,0.953870
215,5a7ac466ea55,59,random_over_sampler,entropy,NaN,10,5,0.966272,0.915753,0.954270,0.933306,0.978761,0.923283,0.951409,0.954270

,configuration_id,seed,fold,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,1,passthrough,gini,10.0,2,1,0.966061,0.935819,0.920616,0.927909,0.987910,0.931002,0.950442,0.920616
1,f555fc62ae6a,27,2,passthrough,gini,10.0,2,1,0.970341,0.944845,0.932083,0.938101,0.989084,0.939673,0.956714,0.932083
2,f555fc62ae6a,27,3,passthrough,gini,10.0,2,1,0.964936,0.935434,0.917611,0.926080,0.987974,0.927374,0.948804,0.917611
3,f555fc62ae6a,32,1,passthrough,gini,10.0,2,1,0.966610,0.939535,0.917688,0.927989,0.986445,0.930564,0.951244,0.917688
4,f555fc62ae6a,32,2,passthrough,gini,10.0,2,1,0.971055,0.942703,0.934682,0.938580,0.990621,0.940038,0.957763,0.934682
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,5a7ac466ea55,32,2,random_over_sampler,entropy,NaN,10,5,0.966720,0.915984,0.955717,0.934223,0.979624,0.924926,0.952077,0.955717
644,5a7ac466ea55,32,3,random_over_sampler,entropy,NaN,10,5,0.965787,0.914374,0.953846,0.932286,0.978194,0.921666,0.950717,0.953846
645,5a7ac466ea55,59,1,random_over_sampler,entropy,NaN,10,5,0.967131,0.919043,0.954140,0.935314,0.978286,0.924308,0.952550,0.954140
646,5a7ac466ea55,59,2,random_over_sampler,entropy,NaN,10,5,0.966226,0.913277,0.955800,0.932348,0.980143,0.923696,0.951470,0.955800
647,5a7ac466ea55,59,3,random_over_sampler,entropy,NaN,10,5,0.965458,0.914939,0.952869,0.932257,0.977854,0.921844,0.950206,0.952869

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,34fdea955c76,passthrough,entropy,20.0,10,1,0.97135 ± 0.00058,0.94431 ± 0.00155,0.93997 ± 0.00120,0.94202 ± 0.00116,0.98059 ± 0.00049,0.93427 ± 0.00178,0.95823 ± 0.00084,0.93997 ± 0.00120

## Random Forest

In [4]:
load_and_display_cross_validation_statistics(
    artifact_directory / "random_forest",
)

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,490871c4e714,passthrough,200,20.0,5,1,0.951756,0.952294,0.951867,0.97624 ± 0.00016,0.95491 ± 0.00056,0.94928 ± 0.00042,0.95197 ± 0.00028,0.99605 ± 0.00008,0.97175 ± 0.00050,0.96535 ± 0.00024,0.94928 ± 0.00042
1,1f17b943c837,passthrough,100,20.0,5,1,0.951661,0.952148,0.951887,0.97616 ± 0.00012,0.95493 ± 0.00059,0.94912 ± 0.00053,0.95190 ± 0.00024,0.99590 ± 0.00005,0.97146 ± 0.00071,0.96523 ± 0.00017,0.94912 ± 0.00053
2,a527f6806362,passthrough,200,20.0,2,1,0.951402,0.952235,0.951957,0.97617 ± 0.00010,0.95420 ± 0.00047,0.94976 ± 0.00110,0.95186 ± 0.00042,0.99600 ± 0.00011,0.97157 ± 0.00054,0.96524 ± 0.00016,0.94976 ± 0.00110
3,18ddbe67ac64,passthrough,100,20.0,2,1,0.951293,0.951775,0.952007,0.97613 ± 0.00006,0.95434 ± 0.00051,0.94931 ± 0.00113,0.95169 ± 0.00036,0.99576 ± 0.00007,0.97124 ± 0.00058,0.96518 ± 0.00009,0.94931 ± 0.00113
4,d807ca23d756,passthrough,100,20.0,10,1,0.951073,0.951641,0.951165,0.97582 ± 0.00017,0.95477 ± 0.00058,0.94807 ± 0.00054,0.95129 ± 0.00031,0.99596 ± 0.00013,0.97145 ± 0.00062,0.96473 ± 0.00025,0.94807 ± 0.00054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,9d16f32867b9,random_over_sampler,200,10.0,5,5,0.936579,0.937476,0.936568,0.96815 ± 0.00025,0.91882 ± 0.00051,0.96006 ± 0.00062,0.93687 ± 0.00052,0.99540 ± 0.00006,0.96420 ± 0.00048,0.95405 ± 0.00035,0.96006 ± 0.00062
68,fa06bde346dd,random_over_sampler,200,10.0,2,5,0.936579,0.937476,0.936568,0.96815 ± 0.00025,0.91882 ± 0.00051,0.96006 ± 0.00062,0.93687 ± 0.00052,0.99540 ± 0.00006,0.96420 ± 0.00048,0.95405 ± 0.00035,0.96006 ± 0.00062
69,1d9206f8f0fa,random_over_sampler,100,10.0,5,5,0.936157,0.937300,0.936556,0.96808 ± 0.00034,0.91847 ± 0.00074,0.96010 ± 0.00088,0.93667 ± 0.00058,0.99538 ± 0.00005,0.96429 ± 0.00065,0.95396 ± 0.00050,0.96010 ± 0.00088
70,ceb3444509db,random_over_sampler,100,10.0,10,5,0.936157,0.937300,0.936556,0.96808 ± 0.00034,0.91847 ± 0.00074,0.96010 ± 0.00088,0.93667 ± 0.00058,0.99538 ± 0.00005,0.96429 ± 0.00065,0.95396 ± 0.00050,0.96010 ± 0.00088
71,e3b9356fe588,random_over_sampler,100,10.0,2,5,0.936157,0.937300,0.936556,0.96808 ± 0.00034,0.91847 ± 0.00074,0.96010 ± 0.00088,0.93667 ± 0.00058,0.99538 ± 0.00005,0.96429 ± 0.00065,0.95396 ± 0.00050,0.96010 ± 0.00088

,configuration_id,seed,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,df61f3a5c0de,27,passthrough,100,10.0,2,1,0.971622,0.957865,0.927456,0.941333,0.995382,0.965813,0.958562,0.927456
1,df61f3a5c0de,32,passthrough,100,10.0,2,1,0.971905,0.958917,0.928296,0.942249,0.995438,0.967389,0.958980,0.928296
2,df61f3a5c0de,59,passthrough,100,10.0,2,1,0.971677,0.958099,0.927502,0.941438,0.995486,0.967100,0.958646,0.927502
3,c3125a46f515,27,passthrough,100,10.0,2,5,0.971228,0.956433,0.927025,0.940486,0.995311,0.965541,0.957987,0.927025
4,c3125a46f515,32,passthrough,100,10.0,2,5,0.970936,0.958282,0.923985,0.939369,0.995307,0.965944,0.957564,0.923985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,976588e868ef,32,random_over_sampler,200,NaN,10,1,0.972737,0.934976,0.957232,0.945458,0.992570,0.961176,0.960459,0.957232
212,976588e868ef,59,random_over_sampler,200,NaN,10,1,0.972353,0.933417,0.956237,0.944114,0.992571,0.960144,0.959910,0.956237
213,03948c1c012b,27,random_over_sampler,200,NaN,10,5,0.972454,0.928560,0.963771,0.944661,0.995620,0.969432,0.960226,0.963771
214,03948c1c012b,32,random_over_sampler,200,NaN,10,5,0.972426,0.928775,0.964121,0.944996,0.995769,0.970130,0.960182,0.964121
215,03948c1c012b,59,random_over_sampler,200,NaN,10,5,0.972216,0.928144,0.963736,0.944438,0.995875,0.969916,0.959882,0.963736

,configuration_id,seed,fold,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,df61f3a5c0de,27,1,passthrough,100,10.0,2,1,0.972591,0.960542,0.928672,0.943238,0.995648,0.967253,0.959984,0.928672
1,df61f3a5c0de,27,2,passthrough,100,10.0,2,1,0.970451,0.956237,0.923332,0.938107,0.994705,0.962954,0.956850,0.923332
2,df61f3a5c0de,27,3,passthrough,100,10.0,2,1,0.971823,0.956816,0.930364,0.942654,0.995793,0.967233,0.958854,0.930364
3,df61f3a5c0de,32,1,passthrough,100,10.0,2,1,0.972317,0.961276,0.928366,0.943280,0.995839,0.969560,0.959590,0.928366
4,df61f3a5c0de,32,2,passthrough,100,10.0,2,1,0.972756,0.958738,0.929882,0.942978,0.995750,0.969079,0.960222,0.929882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,03948c1c012b,32,2,random_over_sampler,200,NaN,10,5,0.972893,0.928215,0.966020,0.945566,0.996103,0.971485,0.960903,0.966020
644,03948c1c012b,32,3,random_over_sampler,200,NaN,10,5,0.971521,0.927988,0.963297,0.944069,0.995071,0.966300,0.958870,0.963297
645,03948c1c012b,59,1,random_over_sampler,200,NaN,10,5,0.973222,0.930096,0.965773,0.946559,0.996062,0.971431,0.961325,0.965773
646,03948c1c012b,59,2,random_over_sampler,200,NaN,10,5,0.971713,0.926073,0.962559,0.942678,0.996037,0.967713,0.959190,0.962559
647,03948c1c012b,59,3,random_over_sampler,200,NaN,10,5,0.971713,0.928262,0.962875,0.944076,0.995525,0.970604,0.959131,0.962875

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,490871c4e714,passthrough,200,20.0,5,1,0.97624 ± 0.00016,0.95491 ± 0.00056,0.94928 ± 0.00042,0.95197 ± 0.00028,0.99605 ± 0.00008,0.97175 ± 0.00050,0.96535 ± 0.00024,0.94928 ± 0.00042

## XGBoost

In [5]:
load_and_display_cross_validation_statistics(
    artifact_directory / "xgboost",
)

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,17edbfb766e1,passthrough,200,6,0.10,1,0.8,0.952853,0.953710,0.953203,0.97662 ± 0.00016,0.95486 ± 0.00029,0.95179 ± 0.00070,0.95326 ± 0.00043,0.99649 ± 0.00007,0.97320 ± 0.00056,0.96591 ± 0.00023,0.95179 ± 0.00070
1,ce27fc414a86,passthrough,200,6,0.10,1,1.0,0.952159,0.952599,0.952933,0.97632 ± 0.00022,0.95502 ± 0.00065,0.95030 ± 0.00117,0.95256 ± 0.00039,0.99640 ± 0.00009,0.97257 ± 0.00051,0.96546 ± 0.00033,0.95030 ± 0.00117
2,f8849103f357,passthrough,200,6,0.10,5,0.8,0.952464,0.952565,0.952618,0.97632 ± 0.00009,0.95491 ± 0.00041,0.95032 ± 0.00042,0.95255 ± 0.00008,0.99646 ± 0.00008,0.97277 ± 0.00081,0.96546 ± 0.00013,0.95032 ± 0.00042
3,e01755c775a3,passthrough,200,6,0.10,5,1.0,0.952027,0.952584,0.952796,0.97618 ± 0.00014,0.95483 ± 0.00016,0.95026 ± 0.00063,0.95247 ± 0.00040,0.99639 ± 0.00011,0.97229 ± 0.00068,0.96526 ± 0.00020,0.95026 ± 0.00063
4,3153d302d9ca,passthrough,200,6,0.05,1,0.8,0.950558,0.950191,0.950492,0.97531 ± 0.00011,0.95457 ± 0.00043,0.94653 ± 0.00069,0.95041 ± 0.00020,0.99624 ± 0.00006,0.97140 ± 0.00065,0.96399 ± 0.00015,0.94653 ± 0.00069
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,7796522caade,random_over_sampler,100,3,0.10,1,1.0,0.917147,0.918235,0.918394,0.95873 ± 0.00030,0.89499 ± 0.00071,0.95104 ± 0.00062,0.91793 ± 0.00068,0.99452 ± 0.00004,0.95606 ± 0.00011,0.94092 ± 0.00042,0.95104 ± 0.00062
60,0afd3dd057f0,random_over_sampler,100,3,0.05,5,0.8,0.909505,0.909790,0.909177,0.95458 ± 0.00019,0.88800 ± 0.00033,0.94158 ± 0.00022,0.90949 ± 0.00031,0.99282 ± 0.00003,0.94979 ± 0.00012,0.93496 ± 0.00026,0.94158 ± 0.00022
61,31a85cb43088,random_over_sampler,100,3,0.05,1,0.8,0.909605,0.909446,0.908651,0.95449 ± 0.00023,0.88763 ± 0.00044,0.94165 ± 0.00038,0.90923 ± 0.00051,0.99281 ± 0.00001,0.94971 ± 0.00018,0.93484 ± 0.00031,0.94165 ± 0.00038
62,693e0b59ff1a,random_over_sampler,100,3,0.05,5,1.0,0.909379,0.908530,0.909153,0.95443 ± 0.00030,0.88743 ± 0.00062,0.94145 ± 0.00010,0.90902 ± 0.00044,0.99279 ± 0.00003,0.94976 ± 0.00018,0.93476 ± 0.00041,0.94145 ± 0.00010
63,74217161e39c,random_over_sampler,100,3,0.05,1,1.0,0.909108,0.908737,0.909186,0.95436 ± 0.00011,0.88734 ± 0.00045,0.94160 ± 0.00018,0.90901 ± 0.00024,0.99280 ± 0.00003,0.94987 ± 0.00002,0.93468 ± 0.00014,0.94160 ± 0.00018

,configuration_id,seed,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f3ea52a0aee0,27,passthrough,100,3,0.05,1,0.8,0.963967,0.951313,0.903967,0.923937,0.992811,0.951054,0.947350,0.903967
1,f3ea52a0aee0,32,passthrough,100,3,0.05,1,0.8,0.963921,0.950416,0.903710,0.923369,0.992783,0.950657,0.947284,0.903710
2,f3ea52a0aee0,59,passthrough,100,3,0.05,1,0.8,0.963903,0.950574,0.904246,0.923786,0.992738,0.951120,0.947256,0.904246
3,c85e973cb979,27,passthrough,100,3,0.05,1,1.0,0.963720,0.949966,0.903462,0.923062,0.992588,0.949868,0.946988,0.903462
4,c85e973cb979,32,passthrough,100,3,0.05,1,1.0,0.963217,0.948395,0.901776,0.921398,0.992674,0.949734,0.946247,0.901776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,333beb896e6e,32,random_over_sampler,200,6,0.10,5,0.8,0.971951,0.925801,0.965850,0.943913,0.996229,0.971243,0.959600,0.965850
188,333beb896e6e,59,random_over_sampler,200,6,0.10,5,0.8,0.972116,0.926944,0.965875,0.944626,0.996373,0.971213,0.959823,0.965875
189,b0ee5d588d22,27,random_over_sampler,200,6,0.10,5,1.0,0.971174,0.924446,0.964959,0.942710,0.996034,0.970028,0.958492,0.964959
190,b0ee5d588d22,32,random_over_sampler,200,6,0.10,5,1.0,0.971923,0.926135,0.965648,0.944026,0.996219,0.971040,0.959552,0.965648
191,b0ee5d588d22,59,random_over_sampler,200,6,0.10,5,1.0,0.971896,0.926293,0.966069,0.944306,0.996281,0.971076,0.959520,0.966069

,configuration_id,seed,fold,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f3ea52a0aee0,27,1,passthrough,100,3,0.05,1,0.8,0.965430,0.953217,0.907365,0.927053,0.993030,0.952879,0.949492,0.907365
1,f3ea52a0aee0,27,2,passthrough,100,3,0.05,1,0.8,0.963071,0.949280,0.902677,0.922079,0.992197,0.947600,0.946036,0.902677
2,f3ea52a0aee0,27,3,passthrough,100,3,0.05,1,0.8,0.963400,0.951443,0.901860,0.922678,0.993207,0.952684,0.946522,0.901860
3,f3ea52a0aee0,32,1,passthrough,100,3,0.05,1,0.8,0.964580,0.953756,0.903178,0.924011,0.993345,0.955228,0.948259,0.903178
4,f3ea52a0aee0,32,2,passthrough,100,3,0.05,1,0.8,0.965238,0.953023,0.907630,0.926737,0.993015,0.951634,0.949216,0.907630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,b0ee5d588d22,32,2,random_over_sampler,200,6,0.10,5,1.0,0.972042,0.924830,0.967682,0.944230,0.996560,0.973471,0.959786,0.967682
572,b0ee5d588d22,32,3,random_over_sampler,200,6,0.10,5,1.0,0.971384,0.926421,0.963419,0.943196,0.995568,0.966974,0.958731,0.963419
573,b0ee5d588d22,59,1,random_over_sampler,200,6,0.10,5,1.0,0.972838,0.928067,0.969347,0.946915,0.996329,0.971007,0.960893,0.969347
574,b0ee5d588d22,59,2,random_over_sampler,200,6,0.10,5,1.0,0.970616,0.922188,0.963151,0.940559,0.996327,0.969411,0.957721,0.963151
575,b0ee5d588d22,59,3,random_over_sampler,200,6,0.10,5,1.0,0.972234,0.928623,0.965710,0.945446,0.996186,0.972809,0.959945,0.965710

,configuration_id,sampler,classifier__n_estimators,classifier__max_depth,classifier__learning_rate,classifier__min_child_weight,classifier__subsample,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,17edbfb766e1,passthrough,200,6,0.1,1,0.8,0.97662 ± 0.00016,0.95486 ± 0.00029,0.95179 ± 0.00070,0.95326 ± 0.00043,0.99649 ± 0.00007,0.97320 ± 0.00056,0.96591 ± 0.00023,0.95179 ± 0.00070