# Validação

In [1]:
from pathlib import Path

from reporting.cross_validation import (
    load_and_display_cross_validation_statistics,
)

In [2]:
artifact_directory = Path("_artifacts") / "genis" / "decision_tree"


load_and_display_cross_validation_statistics(artifact_directory)

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,seed_27_macro_f1,seed_32_macro_f1,seed_59_macro_f1,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,1cbc00d06004,passthrough,gini,20.0,2,1,0.999881,0.999823,0.999806,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004
1,98aa19114822,passthrough,gini,NaN,2,1,0.999881,0.999823,0.999806,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004
2,1f2e9955a969,passthrough,gini,20.0,5,1,0.999874,0.999811,0.999806,0.99994 ± 0.00001,0.99983 ± 0.00003,0.99983 ± 0.00005,0.99983 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99982 ± 0.00004,0.99983 ± 0.00005
3,5b7f649f2af0,passthrough,gini,NaN,5,1,0.999874,0.999811,0.999806,0.99994 ± 0.00001,0.99983 ± 0.00003,0.99983 ± 0.00005,0.99983 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99982 ± 0.00004,0.99983 ± 0.00005
4,03ff75232577,random_over_sampler,gini,20.0,5,1,0.999852,0.999741,0.999853,0.99994 ± 0.00001,0.99983 ± 0.00006,0.99980 ± 0.00007,0.99982 ± 0.00006,0.99989 ± 0.00003,0.99964 ± 0.00013,0.99984 ± 0.00004,0.99980 ± 0.00007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,e49f974c2959,passthrough,entropy,NaN,10,5,0.999618,0.999645,0.999592,0.99987 ± 0.00001,0.99963 ± 0.00004,0.99961 ± 0.00002,0.99962 ± 0.00003,0.99986 ± 0.00001,0.99958 ± 0.00004,0.99962 ± 0.00003,0.99961 ± 0.00002
68,eb1b7735c06a,passthrough,entropy,NaN,5,5,0.999618,0.999645,0.999592,0.99987 ± 0.00001,0.99963 ± 0.00004,0.99961 ± 0.00002,0.99962 ± 0.00003,0.99986 ± 0.00001,0.99958 ± 0.00004,0.99962 ± 0.00003,0.99961 ± 0.00002
69,497adfad464f,passthrough,gini,10.0,10,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001
70,a55c9887c1a2,passthrough,gini,10.0,5,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001
71,c55590c695f3,passthrough,gini,10.0,2,5,0.999579,0.999607,0.999560,0.99981 ± 0.00001,0.99978 ± 0.00003,0.99938 ± 0.00001,0.99958 ± 0.00002,0.99962 ± 0.00002,0.99930 ± 0.00002,0.99946 ± 0.00002,0.99938 ± 0.00001

,configuration_id,seed,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,passthrough,gini,10.0,2,1,0.999830,0.999846,0.999428,0.999637,0.999645,0.999362,0.999506,0.999428
1,f555fc62ae6a,32,passthrough,gini,10.0,2,1,0.999827,0.999844,0.999396,0.999620,0.999589,0.999286,0.999496,0.999396
2,f555fc62ae6a,59,passthrough,gini,10.0,2,1,0.999817,0.999832,0.999392,0.999612,0.999614,0.999302,0.999466,0.999392
3,c55590c695f3,27,passthrough,gini,10.0,2,5,0.999813,0.999777,0.999381,0.999579,0.999633,0.999318,0.999456,0.999381
4,c55590c695f3,32,passthrough,gini,10.0,2,5,0.999820,0.999821,0.999394,0.999607,0.999588,0.999275,0.999476,0.999394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,d5925f8116be,32,random_over_sampler,entropy,NaN,10,1,0.999922,0.999768,0.999704,0.999736,0.999830,0.999491,0.999773,0.999704
212,d5925f8116be,59,random_over_sampler,entropy,NaN,10,1,0.999895,0.999665,0.999658,0.999661,0.999803,0.999349,0.999694,0.999658
213,5a7ac466ea55,27,random_over_sampler,entropy,NaN,10,5,0.999925,0.999785,0.999743,0.999764,0.999852,0.999571,0.999782,0.999743
214,5a7ac466ea55,32,random_over_sampler,entropy,NaN,10,5,0.999915,0.999734,0.999712,0.999723,0.999838,0.999503,0.999753,0.999712
215,5a7ac466ea55,59,random_over_sampler,entropy,NaN,10,5,0.999881,0.999598,0.999648,0.999623,0.999802,0.999299,0.999654,0.999648

,configuration_id,seed,fold,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy,precision,recall,macro_f1,roc_auc,pr_auc,mcc,balanced_accuracy
0,f555fc62ae6a,27,1,passthrough,gini,10.0,2,1,0.999827,0.999884,0.999444,0.999664,0.999644,0.999377,0.999496,0.999444
1,f555fc62ae6a,27,2,passthrough,gini,10.0,2,1,0.999827,0.999768,0.999427,0.999597,0.999616,0.999279,0.999496,0.999427
2,f555fc62ae6a,27,3,passthrough,gini,10.0,2,1,0.999837,0.999886,0.999413,0.999649,0.999675,0.999429,0.999525,0.999413
3,f555fc62ae6a,32,1,passthrough,gini,10.0,2,1,0.999878,0.999882,0.999569,0.999726,0.999705,0.999482,0.999644,0.999569
4,f555fc62ae6a,32,2,passthrough,gini,10.0,2,1,0.999837,0.999852,0.999448,0.999649,0.999635,0.999345,0.999525,0.999448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,5a7ac466ea55,32,2,random_over_sampler,entropy,NaN,10,5,0.999949,0.999873,0.999841,0.999857,0.999907,0.999762,0.999852,0.999841
644,5a7ac466ea55,32,3,random_over_sampler,entropy,NaN,10,5,0.999878,0.999610,0.999530,0.999570,0.999734,0.999171,0.999644,0.999530
645,5a7ac466ea55,59,1,random_over_sampler,entropy,NaN,10,5,0.999888,0.999649,0.999564,0.999607,0.999757,0.999242,0.999674,0.999564
646,5a7ac466ea55,59,2,random_over_sampler,entropy,NaN,10,5,0.999837,0.999455,0.999664,0.999559,0.999795,0.999160,0.999526,0.999664
647,5a7ac466ea55,59,3,random_over_sampler,entropy,NaN,10,5,0.999919,0.999689,0.999717,0.999703,0.999853,0.999496,0.999763,0.999717

,configuration_id,sampler,classifier__criterion,classifier__max_depth,classifier__min_samples_split,classifier__min_samples_leaf,accuracy (mean ± std),precision (mean ± std),recall (mean ± std),macro_f1 (mean ± std),roc_auc (mean ± std),pr_auc (mean ± std),mcc (mean ± std),balanced_accuracy (mean ± std)
0,1cbc00d06004,passthrough,gini,20.0,2,1,0.99994 ± 0.00001,0.99985 ± 0.00003,0.99983 ± 0.00004,0.99984 ± 0.00004,0.99990 ± 0.00003,0.99969 ± 0.00008,0.99983 ± 0.00004,0.99983 ± 0.00004